# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
r_github_packages:
  - r-lib/covr

script:
  - R -e 'install.packages("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(tarball = ".")'
  skip_cleanup: true

after_success:
  - Rscript -e 'covr::codecov()'
